"""Diagnosis 설정 모듈."""
from .settings import (
    DIAGNOSIS_CONFIG,
    DiagnosisConfig,
    TaskScoreWeights,
    ScoreThresholds,
    TaskPolicy,
    LLMPolicy,
    get_health_level,
    get_onboarding_level,
    HealthLevel,
    OnboardingLevel,
    Difficulty,
    TaskKind,
    TaskIntent,
)
from .metrics import DiagnosisMetrics, LLMTimer, diagnosis_metrics
from .config_loader import (
    load_diagnosis_config,
    get_config_hash,
    reload_config,
    get_marketing_config,
    get_consilience_config,
    get_freshness_config,
    get_docs_config,
    get_gate_config,
    get_tech_patterns,
    get_marketing_keywords,
    get_readme_preference,
)

__all__ = [
    "DIAGNOSIS_CONFIG",
    "DiagnosisConfig",
    "DiagnosisMetrics",
    "LLMTimer",
    "diagnosis_metrics",
    "get_health_level",
    "get_onboarding_level",
    "HealthLevel",
    "OnboardingLevel",
    "Difficulty",
    "TaskKind",
    "TaskIntent",
    # v2 config loader
    "load_diagnosis_config",
    "get_config_hash",
    "reload_config",
    "get_marketing_config",
    "get_consilience_config",
    "get_freshness_config",
    "get_docs_config",
    "get_gate_config",
    "get_tech_patterns",
    "get_marketing_keywords",
    "get_readme_preference",
]
